# Generated by Django 5.1.3 on 2026-07-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Email", models.EmailField(max_length=254, unique=True)),
                ("Password", models.CharField(max_length=100)),
            ],
        ),
    ]
